Updating dependencies to fix CVEs has introduced an issue not immediately seen in the update:
thread 'main' (66669) panicked at /home/max/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/opentelemetry-jaeger-0.19.0/src/exporter/runtime.rs:35:12:
Registering a blocking socket with the tokio runtime is unsupported. If you wish to do anyways, please add `--cfg tokio_allow_from_blocking_fd` to your RUSTFLAGS. See github.com/tokio-rs/tokio/issues/7172 for details.

Updating RUSTFLAGS seeing as Reductionist has always worked this way, needs to be addressed independently.